live_config_reload = true

# Dracula theme
import = [
    "~/.config/alacritty/themes/dracula.toml"
]

[window]
opacity = 0.7
blur = true
padding = { x = 10, y = 10 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "ExtraLight" }
bold = { style = "Medium" }
size = 13

