live_config_reload = true

# Dracula theme
import = [
    "~/.config/alacritty/themes/dracula.toml"
]

[window]
opacity = 0.85
blur = true
padding = { x = 10, y = 10 }
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "ExtraLight" }
bold = { style = "Medium" }
size = 13
