general.live_config_reload = true

# Dracula theme
general.import = [
    '~/.config/alacritty/themes/dracula.toml'
]

[window]
opacity = 0.95
blur = true
padding = { x = 10, y = 10 }
dynamic_title = true

[font]
size = 13

[font.normal]
family = 'JetBrainsMono Nerd Font'
style = 'ExtraLight'

[font.bold]
style = 'Medium'

[env]
WINIT_X11_SCALE_FACTOR = '1.5'
